apiVersion: v1
kind: Service
metadata:
  labels:
    app: vcluster-etcd
    release: k3s-ha
  name: k3s-ha-etcd
  namespace: vcluster-k3s-ha
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: etcd
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    app: vcluster-etcd
    release: k3s-ha
  sessionAffinity: None
  type: ClusterIP
